- name: Run Doxygen
  run: doxygen docs/Doxyfile

- name: Check html output
  run: |
    ls -la docs/html
    test -f docs/html/index.html

- name: Add nojekyll
  run: touch docs/html/.nojekyll

- name: Deploy
  uses: peaceiris/actions-gh-pages@v4
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_branch: gh-pages
    publish_dir: docs/html
    force_orphan: true